console.log("42 is a " + typeof "42")
console.log("42 is a " + typeof 42 )
console.log("42 is an " + typeof {})
console.log({} + " is an " + typeof {})
console.log("true is a " + typeof true)
console.log("undefined is an " + typeof undefined)